title: "IA Generativa en Investigación Académica: Base de Datos por "
description: "Base de datos estructurada sobre el uso de inteligencia artificial generativa (IAG) en investigación académica y docencia universitaria en América Lat"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/ia-generativa-en-investigacion-academica-base-de-datos-por-variables-de-uso-perc"
